name: listy_chef
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0 # TODO обновить до 3.8.0, когда обновится yaru

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  go_router: ^15.1.2
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  rx_shared_preferences: ^4.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_svg: ^2.1.0
  flutter_bloc: ^9.1.1
  fast_immutable_collections: ^11.0.4
  dartx: ^1.2.0
  yaru: ^7.0.0
  fluent_ui: ^4.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
          style: italic
